[build]
builder = "nixpacks"

[build.nixpacks]
plan = "maven"

[deploy]
startCommand = "java -Xmx400m -Xms200m -Dserver.port=$PORT -jar target/*.jar"
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
