[build]
builder = "nixpacks"

[build.nixpacks]
plan = "maven"

[deploy]
startCommand = "java -Xmx512m -Dserver.port=$PORT -jar target/*.jar"
healthcheckPath = "/health"
healthcheckTimeout = 600
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
